import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import { Flex, Text } from "@chakra-ui/react";
import  GameBoard  from "@/components/GameBoard";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Game7.io Take Home Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Flex className={styles.main} height="100vh" p={10}>
          <Text fontSize="6xl">Memory Cards Game by Memo Khoury</Text>
          <GameBoard />
        </Flex>
      </main>
    </>
  );
}
